<?php

/**
 * @file
 * Contains symmetri_container.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function symmetri_container_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the symmetri_container module.
    case 'help.page.symmetri_container':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Define an entity type for holding other content') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function symmetri_container_theme() {
  $theme = [];
  $theme['container_entity'] = [
    'render element' => 'elements',
    'file' => 'container_entity.page.inc',
    'template' => 'container_entity',
  ];
  $theme['container_entity_content_add_list'] = [
    'render element' => 'content',
    'variables' => ['content' => NULL],
    'file' => 'container_entity.page.inc',
  ];
  return $theme;
}

/**
 * Implements hook_theme_suggestions_HOOK().
 */
function symmetri_container_theme_suggestions_container_entity(array $variables) {
  $suggestions = [];
  $entity = $variables['elements']['#container_entity'];
  $sanitized_view_mode = strtr($variables['elements']['#view_mode'], '.', '_');

  $suggestions[] = 'container_entity__' . $sanitized_view_mode;
  $suggestions[] = 'container_entity__' . $entity->bundle();
  $suggestions[] = 'container_entity__' . $entity->bundle() . '__' . $sanitized_view_mode;
  $suggestions[] = 'container_entity__' . $entity->id();
  $suggestions[] = 'container_entity__' . $entity->id() . '__' . $sanitized_view_mode;
  return $suggestions;
}
